### ISSUE TITLE
没有选择日期的点击事件吗

### ISSUE THREAD

**Issue by Michael-lu-ke** [llotheo/react-native-big-calendar#1]

**Comment by acro5piano** [comment]
Hi @Michael-lu-ke , thanks for your interest in this repository.

Are you requesting the click event on a particular datetime cell, right?
We'll add the feature in the feature, or any pull requests are welcome.

**Comment by acro5piano** [comment]
Related
https://github.com/llotheo/react-native-big-calendar/issues/2
