### ISSUE TITLE
Changing hours in day

### ISSUE THREAD

**Issue by nicwhitts** [llotheo/react-native-big-calendar#102]
Im trying to customise to use certain hours of the day (for example 9-5)

If i change the `hours` to reflect this. I can draw the grid etc fine

But rendering the current time and the events are not correct.

From my understanding, its due to the logic within the `getRelativeTopInDay` and `getEventCellPositionStyle` methods.

But i'm struggling to figure out the logic. Is there an easy way to make this universal based on the `hours` variable in `utils.js`?

**Comment by nicwhitts** [comment]
Ok i figured it out for my use case.

**Comment by acro5piano** [comment]
How did you solve your problem? If my understanding is correct, you should set `scrollOffsetMinutes`.
Or, are you trying to narrow the hour range? That could be a future feature.
