### ISSUE TITLE
day mode is not working

### ISSUE THREAD

**Issue by PradeepLinkites** [llotheo/react-native-big-calendar#167]
day mode is not working

**Comment by acro5piano** [comment]
Not implemented yet.

**Comment by joelbarron** [comment]
Any solution for this?

**Comment by acro5piano** [comment]
@joelbarron 
Sorry I've been too busy to work on this. I'll try to fix it on this weekend.

**Comment by acro5piano** [comment]
Solved by https://github.com/llotheo/react-native-big-calendar/pull/181 
Thank you @joelbarron
