### ISSUE TITLE
Events not showing

### ISSUE THREAD

**Issue by JoeKlimcak** [llotheo/react-native-big-calendar#241]
Downloaded and ran your example: 

```
import { Calendar } from 'react-native-big-calendar'

const events = [
  {
    title: 'Meeting',
    start: new Date(2020, 9, 23, 10, 0),
    end: new Date(2020, 9, 23, 10, 30),
  },
  {
    title: 'Coffee break',
    start: new Date(2020, 9, 24, 15, 45),
    end: new Date(2020, 9, 24, 16, 30),
  },
]

function App() {
  return <Calendar events={events} height={600} />
}
```

however no matter what I do/change, the calendar will show as empty without any events.

**Comment by acro5piano** [comment]
Hi @JoeKlimcak, thanks for your interest in this project.

This is because JS month not starts on 1 but 0. Try the following Date.

    `start: new Date(2020, 8, 23, 10, 0),`

**Comment by JoeKlimcak** [comment]
Indeed, my bad for not noticing. Thanks very much - great project!
