### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by jtphe** [llotheo/react-native-big-calendar#57]
Hello 🙂
I find the library very interesting, however it lacks some features that I would like to have as a "month" view, a "day" view or display an event when it lasts all day...
So I would like to know if it is possible for you to put a Contribution Guide in the README so that I can contribute to the development of the lib ?

Thank's 😉

**Comment by acro5piano** [comment]
Hi @jtphe 

Thank you for your interest and will to contribute to this project!
I've just created a PR to add contributing guides and community related files, could you check this? I'll merge this soon.

https://github.com/llotheo/react-native-big-calendar/pull/58

Thanks!

**Comment by jtphe** [comment]
Alright, I'll check this !
Thank you 👌🏼

**Comment by jtphe** [comment]
How can I test the modifications ?

**Comment by acro5piano** [comment]
The following commands will do:

```
yarn tsc
yarn lint
yarn test
```

Currently we run them in CI so you don't have to care about it, but in development it will ensure your code has correct code.

**Comment by acro5piano** [comment]
Unit test is not necessary, but calendar logic sometimes becomes very complex so it is useful to make code testable and write unit tests in such logics.
