### ISSUE TITLE
what are the available api keywords

### ISSUE THREAD

**Issue by Minte-grace** [llotheo/react-native-big-calendar#72]

**Comment by acro5piano** [comment]
Sorry we don't have API documentations yet, so please refer to the Storybook and corresponding source code.

- https://react-native-big-calendar.netlify.app
- https://github.com/llotheo/react-native-big-calendar/blob/master/stories/index.stories.tsx

We would like to add a documentation and remaining features later.

**Comment by acro5piano** [comment]
I've added all props to README.md so it is solved.
