### ISSUE TITLE
Clicking a date column (onClickCell feature)

### ISSUE THREAD

**Issue by oportojca** [llotheo/react-native-big-calendar#80]
Hi @acro5piano, hope you're doing well. 

Firstly, I must say the library is very promising. 

I would only like to ask when the onClickCell feature be available?

Thank you very much.

**Comment by acro5piano** [comment]
Hi, thank you for your interest.

Unforunately, `onClickCell` feature is not implemented yet. However, we will implement it in the future, so your PR is really welcome.

**Comment by acro5piano** [comment]
Solved by https://github.com/llotheo/react-native-big-calendar/pull/82
