### ISSUE TITLE
'event' is not defined.

### ISSUE THREAD

**Issue by oportojca** [llotheo/react-native-big-calendar#85]
![image](https://user-images.githubusercontent.com/62530919/81410914-228b2680-9174-11ea-8ac5-128172f935ac.png)

This is what I encountered with latest version.

> This error is located at:
>     in NavigationContainer (at App.js:82)
>     in ThemeProvider (at App.js:81)
>     in Provider (at App.js:80)
>     in App (at renderApplication.js:45)
>     in RCTView (at AppContainer.js:109)
>     in RCTView (at AppContainer.js:135)
>     in AppContainer (at renderApplication.js:39)

**Comment by acro5piano** [comment]
What is your actual code?

**Comment by acro5piano** [comment]
Oh sorry, I confirm the error in React Native environment. will fix soon

**Comment by oportojca** [comment]
Thanks @acro5piano .

**Comment by acro5piano** [comment]
Fixed in v0.3.1.
https://github.com/llotheo/react-native-big-calendar/releases/tag/v0.3.1
