### ISSUE TITLE
Selecting hour slot for 2300-0000 doesn't work

### ISSUE THREAD

**Issue by nicwhitts** [llotheo/react-native-big-calendar#92]
Great job on selecting the slots to create an event.

On react native (iOS), it seems i cannot select the hour 2300-0000 (I'm in week view)

**Comment by acro5piano** [comment]
Thank you for your interest in this project.

Oh I didn't notice this. Will try to figure out the cause.

**Comment by acro5piano** [comment]
That's because the event handler sets `end` to start + 60 minutes, meaning breaking the event cell rendering. fixed it in https://github.com/llotheo/react-native-big-calendar/pull/94.

Thank you for reporting this!
